### ISSUE TITLE
'Empty read_set. Maybe empty {!}?'.format(map_fn)

### ISSUE THREAD

**Issue by fbemm** [PacificBiosciences/FALCON_unzip#104]
Getting this error with the latest Falcon_unzip version. It was run on a "old" assembly that was done 3 months ago. Any idea what is going on? Input files are all in place. 

```
+ python -m falcon_kit.mains.fetch_reads
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/falcon_kit/mains/fetch_reads.py", line 153, in <module>
    main()
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/falcon_kit/mains/fetch_reads.py", line 149, in main
    fetch_ref_and_reads(**vars(args))
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/falcon_kit/mains/fetch_reads.py", line 70, in fetch_ref_and_reads
    assert read_set, 'Empty read_set. Maybe empty {!}?'.format(map_fn)
ValueError: end of format while looking for conversion specifier
touch /ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads/track_reads_done.exit
+ touch /ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads/track_reads_done.exit
2017-12-15 13:07:21,473 - root - DEBUG - CD: '/ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads' -> '/ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads'
2017-12-15 13:07:21,473 - root - DEBUG - CD: '/ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads' -> '/ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads'
2017-12-15 13:07:21,474 - root - CRITICAL - Error in /ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py", line 166, in <module>
    main()
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py", line 158, in main
    run(**vars(parsed_args))
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py", line 112, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py", line 136, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/lib/python2.7/site-packages/pypeflow/do_task.py", line 101, in run_python_func
    do_support.run_bash(script_fn)
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/local/lib/python2.7/site-packages/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /ebio/abt6_projects7/arabidopsis_genomes/data/aare/genome/assembly/falcon/3-unzip/reads/track_reads.sh'
```

**Comment by fbemm** [comment]
"Traceback (most recent call last):
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_unzip.py')()
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 25, in main
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 319, in run
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 195, in unzip_all
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/local/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/ebio/abt6_projects9/abt6_software/bin/falcon/fc_env_171215/local/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])"

**Comment by pb-cdunn** [comment]
Oops. That was not fixed in the latest binary. But it's fixed on the `develop` branch here now (https://github.com/PacificBiosciences/FALCON/commit/ff5dca6ead368cde0529b2e84bd7cf2be6a91ea2). Thanks for the report.

Fortunately, this was only a bug when there was already a crash (an assertion failure).

Note that the latest Falcon (FALCON-integrate/2.0.0) will not work on old assemblies. The directory structure is backward-incompatible.
