### ISSUE TITLE
[ERROR]Task Node(3-unzip/0-phasing/000000F) failed with exit-code=1

### ISSUE THREAD

**Issue by DuskLi** [PacificBiosciences/FALCON_unzip#110]
When I run fc_unzip.py fc_unzip.cfg, some error happen:
```
[INFO]Popen: 'bash -C /cloud/software/falcon/fc_env_180313/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /cloud/software/falcon/src/FALCON-sv2/3-unzip/0-phasing/000000F/run-P3540e6096f1e47.bash.stdout 2>| /cloud/software/falcon/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/3-unzip/0sh.stderr'
[INFO]sleep 0.2s
[INFO]sleep 0.3s
**[ERROR]Task Node(3-unzip/0-phasing/000000F) failed with exit-code=1**
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 4
**[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000000F)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/cloud/software/falcon/fc_env_180313/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.0.0', 'console_scripts', 'fc_unzip.py')()
  File "/scratch/cdunn/repo/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
  File "/scratch/cdunn/repo/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 99, in run
  File "/scratch/cdunn/repo/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 33, in unzip_all
  File "/scratch/cdunn/repo/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 266, in run_workflow
  File "/cloud/software/falcon/fc_env_180313/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/cloud/software/falcon/fc_env_180313/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000000F)])**
```
What should I do for fix this issuse?

Best regards
Thanks

**Comment by pb-cdunn** [comment]
That's the stack-trace for the workflow. You need to look for stderr somewhere under `3-unzip/0-phasing/000000F`. The problem will probably become obvious.

**Comment by rob123king** [comment]
I have the same and the stderr didn't give any help. did you find a solution???

**Comment by biolittleboy** [comment]
Hi,
I also encountered this problem, how can you solve it?

**Comment by coreywischmeyer** [comment]
Installed the conda package today and got the following error:

```
[INFO]samtools ['1', '9'] is >= 1.3
[WARNING]CD: '0-rawreads' <- '/scratch/FALCON-examples/run/greg200k-sv2'
[WARNING]CD: '0-rawreads' -> '/scratch/FALCON-examples/run/greg200k-sv2'
[WARNING]CD: '1-preads_ovl' <- '/scratch/FALCON-examples/run/greg200k-sv2'
[WARNING]CD: '1-preads_ovl' -> '/scratch/FALCON-examples/run/greg200k-sv2'
[INFO]Falcon directories up-to-date.
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.blocking' from '/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/blocking.pyc'>
[INFO]job_type='string', (default)job_defaults={'pwatcher_type': 'blocking', 'use_tmpdir': False, 'job_type': 'string', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': '4', 'njobs': '8'}, use_tmpdir=False, squash=False, job_name_style=0
[INFO]Setting max_jobs to 8; was None
[INFO]config=
 {'Unzip': {'polish_vc_ignore_error': False, 'input_bam_fofn': 'input_bam.fofn', 'input_fofn': 'input.fofn', 'polish_use_blasr': False}, 'job.step.unzip.blasr_aln': {'njobs': '2', 'NPROC': '16'}, 'max_n_open_files': '1000', 'job.step.unzip.hasm': {'njobs': '1', 'NPROC': '48'}, 'General': {'max_n_open_files': '1000'}, 'job.step.unzip.track_reads': {'njobs': '1', 'NPROC': '48'}, 'job.step.unzip.phasing': {'njobs': '16', 'NPROC': '2'}, 'job.step.unzip.quiver': {'njobs': '2', 'NPROC': '12'}, 'job.defaults': {'pwatcher_type': 'blocking', 'use_tmpdir': False, 'job_type': 'string', 'submit': 'bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}', 'NPROC': '4', 'njobs': '8'}}
[INFO]Num unsatisfied: 0, graph: 5
[INFO]Setting max_jobs to 2; was 8
[INFO]Num unsatisfied: 2, graph: 8
[INFO]About to submit: Node(3-unzip/0-phasing/000000F)
[INFO]Popen: 'bash -C /loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pwatcher/mains/job_start.sh >| /scratch/FALCON-examples/run/greg200k-sv2/3-unzip/0-phasing/000000F/run-Pe8de26fe9ee318.bash.stdout 2>| /scratch/FALCON-examples/run/greg200k-sv2/3-unzip/0-phasing/000000F/run-Pe8de26fe9ee318.bash.stderr'
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.3s -- another 2 loop iterations)
[INFO](slept for another 1.2s -- another 3 loop iterations)
[INFO](slept for another 3.0s -- another 4 loop iterations)
[INFO](slept for another 6.0s -- another 5 loop iterations)
[INFO](slept for another 10.5s -- another 6 loop iterations)
[ERROR]Task Node(3-unzip/0-phasing/000000F) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000000F)])
[ERROR]ready: set([])
        submitted: set([])
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
Traceback (most recent call last):
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==1.1.5', 'console_scripts', 'fc_unzip.py')()
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 29, in main
    unzip.run(**vars(args))
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 184, in run    unzip_all(config, unzip_config_fn)
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 29, in unzip_all
    tasks_unzip.run_workflow(wf, config, unzip_config_fn, rule_writer)
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_unzip/tasks/unzip.py", line 459, in run_workflow
    dist=Dist(NPROC=24, job_dict=config['job.step.unzip.blasr_aln']),
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/falcon_kit/pype.py", line 194, in gen_parallel_tasks
    wf.refreshTargets()
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/loginhome/cwischmeyer/anaconda3/envs/denovo_asm/lib/python2.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/0-phasing/000000F)])
```

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
```

I followed these steps:
```
conda create -n denovo_asm
conda activate denovo_asm
conda install pb-assembly
```

Then the steps listed here: https://github.com/PacificBiosciences/pb-assembly#example-data-set

**Comment by pb-cdunn** [comment]
You would need to look for a stderr file under `3-unzip/0-phasing/000000F`.
