### ISSUE TITLE
Falcon_unzip can't deal with the HGAP4' output

### ISSUE THREAD

**Issue by jun3234** [PacificBiosciences/FALCON_unzip#112]
I have successfuly installed the falcon and falcon_unzip with this Binaries files and manual in https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries. But I can't transform the HGAP4 output to FALCON-compatible directory.
I used the following command in CentOS 7
```sh
$ python -m falcon_kit.mains.hgap4_adapt --job-output-dir=${job_dir}
```
but ,there are issues as following:
```py
WARNING:root:CD: u'0-rawreads/raw-fofn-abs/' <- '/home/smrtanalysis/SF/userdata/jobs_root.default/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0'
WARNING:root:CD: u'0-rawreads/raw-fofn-abs/' -> '/home/smrtanalysis/SF/userdata/jobs_root.default/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0'
WARNING:root:CD: u'0-rawreads/' <- '/home/smrtanalysis/SF/userdata/jobs_root.default/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0'
INFO:__main__:link u'raw_reads.db' to ../../../../../../jobs_root/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0/raw_reads.db
INFO:__main__:link u'.raw_reads.bps' to ../../../../../../jobs_root/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0/.raw_reads.bps
INFO:__main__:link u'.raw_reads.idx' to ../../../../../../jobs_root/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0/.raw_reads.idx
WARNING:root:CD: u'0-rawreads/' -> '/home/smrtanalysis/SF/userdata/jobs_root.default/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0'
Traceback (most recent call last):
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 471, in <module>
    main()
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 466, in main
    symlink(args.job_output_dir)
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 403, in symlink
    task_build_rdb()
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 223, in task_build_rdb
    link(rdir, '.raw_reads.dust.data')
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 198, in link
    assert_exists(os.path.abspath(target))
  File "/home/smrtanalysis/.conda/envs/Falcon_integration/bin/lib/python2.7/site-packages/falcon_kit/mains/hgap4_adapt.py", line 177, in assert_exists
    assert os.path.exists(path), 'File does not exist: {!r}'.format(path)
AssertionError: File does not exist: u'/home/smrtanalysis/SF/userdata/jobs_root/000/000056/tasks/falcon_ns.tasks.task_falcon0_build_rdb-0/.raw_reads.dust.data'
```
I have successfully execute the SMRT analysis and have output, But the are no ".raw_reads.dust.data" files in that directory. And How could I do? rerun the SMRT?

**Comment by pb-cdunn** [comment]
You need to run `hgap4_adapt.py`, which produces a tree of symlinks with the structure expected by unzip. Unfortunately, we have not yet updated hgap4_adapt after recent changes, so cross your fingers. The version of hgap4_adapt in your smrtlink *might* work. You will also need a compatible Falcon-unzip tarball. I think the latest is fine, but I'm not certain. It will have a different version of hgap4_adapt, which also *might* work.
