### ISSUE TITLE
unzip 1-hasm phased_ovlp_to_graph Error

### ISSUE THREAD

**Issue by nottwy** [PacificBiosciences/FALCON_unzip#114]
Dear developer,

I was running falcon-unzip and encountered this problem:
_________________________________________________
python -m falcon_unzip.mains.phased_ovlp_to_graph preads.p_ovl --min_len 2500 > fc.log
++ python -m falcon_unzip.mains.phased_ovlp_to_graph preads.p_ovl --min_len 2500
Traceback (most recent call last):
  File "/home/xxyi/bin/python-2.7.13/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/xxyi/bin/python-2.7.13/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/scratch/cdunn/fork/.git/LOCAL2/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1538, in <module>
  File "/scratch/cdunn/fork/.git/LOCAL2/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1534, in main
  File "/scratch/cdunn/fork/.git/LOCAL2/lib/python2.7/site-packages/falcon_unzip/mains/phased_ovlp_to_graph.py", line 1339, in run
  File "/home/xxyi/bin/FALCON-integrate/fc_env_180307/lib/python2.7/site-packages/networkx/classes/multidigraph.py", line 395, in remove_edge
    "The edge %s-%s is not in the graph." % (u, v))
networkx.exception.NetworkXError: The edge 016034391:E-001041662:E is not in the graph.
_________________________________________________

Could you give me a solution? 3ku.

**Comment by nottwy** [comment]
@pb-jchin ,could you please just give me some advice about how to solve it? 3ku

**Comment by pb-cdunn** [comment]
If you start over with the latest binary release, we might be able to help you.
