### ISSUE TITLE
FALCON_unzip is not working

### ISSUE THREAD

**Issue by ruthfa** [PacificBiosciences/FALCON_unzip#124]
I am trying to use FALCON_unzip but it doesn't work. The program fails at the very begining and I don't know what is the problem. I use a general service so I didn't install directly the program, but I am afraid that it can be an installation problem. My error file is that:

pypeflow 2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]job_type='local', (default)job_defaults={}, use_tmpdir=None, squash=False, job_name_style=0
[INFO]Setting max_jobs to 24; was None
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(3-unzip/reads)
[INFO] starting job Job(jobid='Pe397759b3897de', cmd='/bin/bash run.sh', rundir='/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/3-unzip/reads', options={'MB': 4000, 'job_type': 'local', 'NPROC': 1}) w/ job_type=LOCAL
[INFO]dir: '/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/jobs/Pe397759b3897de'
CALL:
 '/bin/bash /srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/wrappers/run-Pe397759b3897de.bash 1>|stdout 2>|stderr & '
[INFO]pid=109859 pgid=109771 sub-pid=110151
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pe397759b3897de', cmd='/bin/bash run.sh', rundir='/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/3-unzip/reads', options={'MB': 4000, 'job_type': 'local', 'NPROC': 1}), lang_exe='/bin/bash'))
[ERROR]Task Node(3-unzip/reads) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Failed to kill job for heartbeat 'heartbeat-Pe397759b3897de' (which might mean it was already gone): IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.py", line 597, in delete_heartbeat
    bjob.kill(state, heartbeat)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.py", line 272, in kill
    with open(heartbeat_fn) as ifs:
IOError: [Errno 2] No such file or directory: '/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/heartbeats/heartbeat-Pe397759b3897de'
Traceback (most recent call last):
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/bin/fc_unzip.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-unzip==0.4.0', 'fc_unzip.py')
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/EGG-INFO/scripts/fc_unzip.py", line 4, in <module>
    main(sys.argv)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 384, in main
    unzip_all(config)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 219, in unzip_all
    wf.refreshTargets() #force refresh now, will put proper dependence later
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 358, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
pypeflow 2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010
[INFO]In simple_pwatcher_bridge, pwatcher_impl=<module 'pwatcher.fs_based' from '/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.pyc'>
[INFO]job_type='local', (default)job_defaults={}, use_tmpdir=None, squash=False, job_name_style=0
[INFO]Setting max_jobs to 24; was None
[INFO]Num unsatisfied: 1, graph: 1
[INFO]About to submit: Node(3-unzip/reads)
[INFO] starting job Job(jobid='Pe397759b3897de', cmd='/bin/bash run.sh', rundir='/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/3-unzip/reads', options={'MB': 4000, 'job_type': 'local', 'NPROC': 1}) w/ job_type=LOCAL
[INFO]dir: '/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/jobs/Pe397759b3897de'
CALL:
 '/bin/bash /srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/wrappers/run-Pe397759b3897de.bash 1>|stdout 2>|stderr & '
[INFO]pid=22089 pgid=22080 sub-pid=22164
[INFO]Submitted backgroundjob=MetaJobLocal(MetaJob(job=Job(jobid='Pe397759b3897de', cmd='/bin/bash run.sh', rundir='/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/3-unzip/reads', options={'MB': 4000, 'job_type': 'local', 'NPROC': 1}), lang_exe='/bin/bash'))
[INFO](slept for another 0.0s -- another 1 loop iterations)
[INFO](slept for another 0.3s -- another 2 loop iterations)
[INFO](slept for another 1.2s -- another 3 loop iterations)
[ERROR]Task Node(3-unzip/reads) failed with exit-code=256
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
[ERROR]ready: set([])
	submitted: set([])
[ERROR]Failed to kill job for heartbeat 'heartbeat-Pe397759b3897de' (which might mean it was already gone): IOError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.py", line 597, in delete_heartbeat
    bjob.kill(state, heartbeat)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pwatcher/fs_based.py", line 272, in kill
    with open(heartbeat_fn) as ifs:
IOError: [Errno 2] No such file or directory: '/srv/netscratch/irg/grp_stich/Potatodenovo/PacBio_Agriadiploid/FALCON/Test5/mypwatcher/heartbeats/heartbeat-Pe397759b3897de'
Traceback (most recent call last):
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/bin/fc_unzip.py", line 4, in <module>
    __import__('pkg_resources').run_script('falcon-unzip==0.4.0', 'fc_unzip.py')
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1494, in run_script
    exec(code, namespace, namespace)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/EGG-INFO/scripts/fc_unzip.py", line 4, in <module>
    main(sys.argv)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 384, in main
    unzip_all(config)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/falcon_unzip-0.4.0-py2.7.egg/falcon_unzip/unzip.py", line 219, in unzip_all
    wf.refreshTargets() #force refresh now, will put proper dependence later
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 277, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/opt/share/software/packages/FALCON_unzip-0.4.0/pyvirt/local/lib/python2.7/site-packages/pypeflow-2.0.2+git.6f8c77e262659866018c5d4ed9a06e46dfd7f010-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 358, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])

**Comment by pb-cdunn** [comment]
Look into the directory `3-unzip/reads` for `*/*stderr`. That should help.

Also, please use the binaries, not the github source-code.

https://github.com/PacificBiosciences/FALCON_unzip/wiki/Binaries
