### ISSUE TITLE
How to set pbalign tmpdir when running fc-quiver.py

### ISSUE THREAD

**Issue by phillip-mcclurg-driscolls** [PacificBiosciences/FALCON_unzip#127]
When running fc_quiver.py (after successfully running fc_unzip.py) on Greg Conception's test example the run fails because pbalign tries to write to /scratch as the temp directory.  On our machine /scratch is on a small local disk which may overload when I try my full run on blueberry.  Currently it requires sudo rights to write to (as it should).

I need to change the tmpDir option for pbalign through my fc_unzip.cfg file which is identical to Greg's except that I have added I have added to the General section

use_tmpdir = /archive/jenkins_test/pmcclurg/tmp

which is on a large disk - this has worked well for fc_run.cfg, but is not reaching pbalign.  Any suggestions?  Here is the last part of the output for

fc_quiver.py fc_unzip.cfg (from run-Pca989a35bf198c.bash.stderr)

samtools faidx /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_scatter/refs/000000F/ref.fa
+ samtools faidx /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_scatter/refs/000000F/ref.fa
pbalign --tmpDir=/scratch/ --nproc=24 --minAccuracy=0.75 --minLength=50          --minAnchorSize=12 --maxDivergence=30 --concordant --algorithm=blasr          --algorithmOptions=--useQuality --maxHits=1 --hitPolicy=random --seed=1            /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/segregate_scatter/segregated/000000F/000000F.bam /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_scatter/refs/000000F/ref.fa aln-000000F.bam
+ pbalign --tmpDir=/scratch/ --nproc=24 --minAccuracy=0.75 --minLength=50 --minAnchorSize=12 --maxDivergence=30 --concordant --algorithm=blasr --algorithmOptions=--useQuality --maxHits=1 --hitPolicy=random --seed=1 /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/segregate_scatter/segregated/000000F/000000F.bam /archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_scatter/refs/000000F/ref.fa aln-000000F.bam
[Errno 13] Permission denied: '/scratch/tmpSxFEAA'
Traceback (most recent call last):
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbcommand/cli/core.py", line 137, in _pacbio_main_runner
    return_code = exe_main_func(*args, **kwargs)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 284, in args_runner
    return PBAlignRunner(args, output_dataset_type=output_dataset_type).start()
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbcore/util/ToolRunner.py", line 85, in start
    return self.run()
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 234, in run
    self._tempFileManager)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbalign/pbalignrunner.py", line 122, in _createAlignService
    service = BlasrService(args, fileNames, tempFileManager)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbalign/alignservice/align.py", line 122, in __init__
    self._tempFileManager.SetRootDir(self._options.tmpDir)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pbalign/utils/tempfileutil.py", line 91, in SetRootDir
    rootDir = tempfile.mkdtemp(dir=rootDir)
  File "/archive/jenkins_test/pmcclurg/Python-2.7.9/lib/python2.7/tempfile.py", line 333, in mkdtemp
    _os.mkdir(file, 0700)
OSError: [Errno 13] Permission denied: '/scratch/tmpSxFEAA'
touch quiver_done.exit
+ touch quiver_done.exit
2018-06-26 08:50:30,340 - root - WARNING - Call '/bin/bash user_script.sh' returned 512.
2018-06-26 08:50:30,340 - root - WARNING - CD: '/archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_run/000000F' -> '/archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_run/000000F'
2018-06-26 08:50:30,340 - root - WARNING - CD: '/archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_run/000000F' -> '/archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_run/000000F'
2018-06-26 08:50:30,341 - root - CRITICAL - Error in /archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/archive/jenkins_test/pmcclurg/FALCON_unzip/src/FALCON-integrate/FALCON-examples/run/greg200k-sv2/4-quiver/quiver_run/000000F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/archive/jenkins_test/pmcclurg/Python-2.7.9/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/archive/jenkins_test/pmcclurg/Python-2.7.9/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py", line 250, in <module>
    main()
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py", line 242, in main
    run(**vars(parsed_args))
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py", line 236, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py", line 212, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/do_task.py", line 173, in run_bash
    util.system(cmd)
  File "/archive/jenkins_test/pmcclurg/FALCON_unzip/fc_env_180607/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 512.

real    0m1.305s
user    0m1.907s
sys     0m5.424s
+ finish
+ echo 'finish code: 1'

**Comment by pb-cdunn** [comment]
The latest binary release fixes this. And `use_tmpdir=/foo` should work too, if you want it off the network disk.

**Comment by wsuplantpathology** [comment]
Dear @pwmcclurg @pb-cdunn 

I was trying to use fc_quiver.py to polish my assembly, after I successfully finished fc_unzip.py . It seems there needs a config_fn file. But I cannot find examples of such files. DO you have such configure files? Thanks so much.

SIncerely
Chongjing

**Comment by pb-cdunn** [comment]
@wsuplantpathology , 

https://github.com/pb-cdunn/FALCON-examples/blob/master/run/greg200k-sv2/fc_unzip.cfg
