### ISSUE TITLE
AttributeError: 'IntervalTree' object has no attribute 'search'

### ISSUE THREAD

**Issue by hangch123** [PacificBiosciences/FALCON_unzip#141]
falcon-unzip 1.1.4
falcon-kit 1.2.4
pypeflow 2.1.1
Traceback (most recent call last):
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 627, in <module>
    main()
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 624, in main
    run(**vars(args))
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 512, in run
    updated_rid2phase, phase_relation_graph, htig_to_phase = create_new_rid2phase(ctg_id, rid2phase, all_regions, m4, a_paths)
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 91, in create_new_rid2phase
    found_regions = tree.search(reference_start, reference_end)
AttributeError: 'IntervalTree' object has no attribute 'search'
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/home/zy/test3/3-unzip/0-phasing/000627F'
Traceback (most recent call last):
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 116, in <module>
    main()
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 112, in main
    run(**vars(args))
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2018-12-28 13:04:52,395 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2018-12-28 13:04:52,396 - root - WARNING - CD: '/home/zy/test3/3-unzip/0-phasing/000627F' -> '/home/zy/test3/3-unzip/0-phasing/000627F'
2018-12-28 13:04:52,396 - root - WARNING - CD: '/home/zy/test3/3-unzip/0-phasing/000627F' -> '/home/zy/test3/3-unzip/0-phasing/000627F'
2018-12-28 13:04:52,396 - root - CRITICAL - Error in /home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/zy/test3/3-unzip/0-phasing/000627F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/zy/tools/miniconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/zy/tools/miniconda2/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd
+++ pwd
++ echo 'FAILURE. Running top in /home/zy/test3/3-unzip/0-phasing/000627F (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	4m30.479s
user	4m7.588s
sys	0m13.520s
+ finish
+ echo 'finish code: 1'
[run-Pf1ee522fa7b416.bash.zip](https://github.com/PacificBiosciences/FALCON_unzip/files/2714190/run-Pf1ee522fa7b416.bash.zip)

What should I do?

Best regards
Thanks

**Comment by hangch123** [comment]
Used updated Falcon will happen this issue, please help me to solve

**Comment by alejandrotorresn** [comment]
Hi,

This is not a issue. The meta-package pb-assembly does not install all requirements. Basically, You need install pwntools (pip install pwntools).

**Comment by fbemm** [comment]
It does install intervaltree but the wrong version. You need to do the following after activating the conda environment:

conda install intervaltree=2.1.0

**Comment by baozg** [comment]
Thanks for @fbemm , it did work.
