### ISSUE TITLE
Unzip error

### ISSUE THREAD

**Issue by Bromo0562** [PacificBiosciences/FALCON_unzip#145]
I am trying to run unzip locally and I am getting the following error:
```py
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 635, in <module>
    main()
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 632, in main
    run(**vars(args))
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 517, in run
    updated_rid2phase, phase_relation_graph, htig_to_phase = create_new_rid2phase(ctg_id, rid2phase, all_regions, m4, a_paths)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_unzip/proto/main_augment_pb.py", line 94, in create_new_rid2phase
    found_regions = tree.search(reference_start, reference_end)
AttributeError: 'IntervalTree' object has no attribute 'search'
WARNING:root:Call '/bin/bash user_script.sh' returned 256.
WARNING:root:CD: 'uow-00' -> '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F'
Traceback (most recent call last):
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 116, in <module>
    main()
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 112, in main
    run(**vars(args))
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/falcon_kit/mains/generic_run_units_of_work.py", line 65, in run
    pypeflow.do_task.run_bash(script, inputs, outputs, params)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
2019-02-05 17:45:39,792 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2019-02-05 17:45:39,792 - root - WARNING - CD: '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F' -> '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F'
2019-02-05 17:45:39,793 - root - WARNING - CD: '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F' -> '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F'
2019-02-05 17:45:39,793 - root - CRITICAL - Error in /home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 267, in <module>
    main()
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 259, in main
    run(**vars(parsed_args))
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 253, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 228, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/do_task.py", line 187, in run_bash
    util.system(cmd)
  File "/home/watson/.conda/envs/denovo_asm2/lib/python2.7/site-packages/pypeflow/io.py", line 29, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
+++ pwd
++ echo 'FAILURE. Running top in /home/watson/F18FTSUSAT0506_PHAgkxD/assembly_71G2/3-unzip/0-phasing/001499F (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real	5m37,705s
user	5m5,121s
sys	0m20,381s
 returned: 256
```
Is it a latency problem? Somebody has experience in running falcon-unzip locally?

**Comment by pb-cdunn** [comment]
You'd need to look for the task-specific stderr, e.g. under `3-unzip/0-phasing/001499F/`.
