### ISSUE TITLE
[ERROR]Task Node(3-unzip/reads/dump_rawread_ids) failed with exit-code=1

### ISSUE THREAD

**Issue by crkmary** [PacificBiosciences/FALCON_unzip#152]
Hello All,

I am having an error while using falcon_unzip (be installed the pb-assembly), the error is as follows. My genome size is about 3.43Mb.

Thanks a lot for your help.

```
[INFO](slept_ for another 2.9999999999999996s -- another 4 loop iterations)
[INFO](slept for another 10.500000000000002s -- another 6 loop iterations)
[ERROR]Task Node(3-unzip/reads/dump_rawread_ids) failed with exit-code=1
[ERROR]Some tasks are recently_done but not satisfied: {Node(3-unzip/reads/dump_rawread_ids)}
[ERROR]ready: set()
                      submitted: set()
[ERROR]Noop. We cannot kill blocked threads. Hopefully, everything will die on SIGTERM.
[ERROR]Error for run(target=clr, config_fn=fc_unzip.cfg, logging_config_fn=None)
```
```py
Traceback (most recent call last):
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 195, in run
   run_logged(target, config_fn)
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 184, in run_logged
  unzip_all(config, unzip_config_fn)
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_unzip/unzip.py", line 27, in unzip_all
   tasks_unzip.run_workflow(wf, config, unzip_config_fn)
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_unzip/tasks/unzip.py", line 467, in run_workflow
   dist=Dist(NPROC=24, job_dict=config['job.step.unzip.blasr_aln']),
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/falcon_kit/pype.py", line 109, in gen_parallel_tasks
   wf.refreshTargets()
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 278, in refreshTargets
  self._refreshTargets(updateFreq, exitOnFailure)
 File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/simple_pwatcher_bridge.py", line 362, in _refreshTargets
 raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: {Node(3-unzip/reads/dump_rawread_ids)}
```
My Confif file is as follows:

> fc_unzip.cfg
```ini
[General]
max_n_open_files = 1000
> [Unzip]
> input_fofn=` input.fofn
> input_bam_fofn= input_bam.fofn
> #sge_phasing= -pe smp 12 -q bigmem
> #sge_quiver= -pe smp 12 -q sequel-farm
> #sge_track_reads= -pe smp 12 -q default
> #sge_blasr_aln=  -pe smp 24 -q bigmem
> #sge_hasm=  -pe smp 48 -q bigmem
> #unzip_concurrent_jobs = 64
> #quiver_concurrent_jobs = 64
> 
> #unzip_concurrent_jobs = 12
> #quiver_concurrent_jobs = 12
> 
> [job.defaults]
> NPROC=6
> njobs=32
> #job_type = SGE
> job_type = local
> 
> #use_tmpdir = /scratch
> pwatcher_type = blocking
> #job_type = string
> submit = bash -C ${CMD} >| ${STDOUT_FILE} 2>| ${STDERR_FILE}
> 
> #njobs=120
> #njobs=8
> #NPROC=4
> #submit = qsub -S /bin/bash -sync y -V  \

> [job.step.unzip.track_reads]
> njobs=1
> NPROC=48
> [job.step.unzip.blasr_aln]
> njobs=2
> NPROC=16
> [job.step.unzip.phasing]
> njobs=16
> NPROC=2
> [job.step.unzip.hasm]
> njobs=1
> NPROC=48
> [job.step.unzip.quiver]
> njobs=2
> NPROC=12
```
```sh
### run-P8053c4ab3cf5d1.bash.stderr
> executable=${PYPEFLOW_JOB_START_SCRIPT}
> + executable=/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/run-P8053c4ab3cf5d1.bash
> timeout=${PYPEFLOW_JOB_START_TIMEOUT:-60} # wait 60s by default
> + timeout=60
> 

> while [[ ! -x "${executable}" ]]; do
>     if [[ "${timeout}" == "0" ]]; then
>         echo "timed out waiting for (${executable})"
>         exit 77
>     fi
>     echo "not executable: '${executable}', waiting ${timeout}s"
>     sleep 1
>     timeout=$((timeout-1))
> done
> + [[ ! -x /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/run-P8053c4ab3cf5d1.bash ]]
> 
> /bin/bash ${executable}
> + /bin/bash /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/run-P8053c4ab3cf5d1.bash
> + '[' '!' -d /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids ']'
> + cd /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids
> + eval '/bin/bash run.sh'
> ++ /bin/bash run.sh
> export PATH=$PATH:/bin
> + export PATH=/root/miniconda3/envs/dna/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/miniconda3/bin:/root/bin:/bin
> + PATH=/root/miniconda3/envs/dna/bin:/root/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/miniconda3/bin:/root/bin:/bin
> cd /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids
> + cd /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids
> /bin/bash task.sh
> + /bin/bash task.sh
> pypeflow 2.3.0
> 2019-10-12 10:16:58,020 - root - DEBUG - Running "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/task.json"
> 2019-10-12 10:16:58,021 - root - DEBUG - Checking existence of '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/task.json' with timeout=30
> 2019-10-12 10:16:58,021 - root - DEBUG - Loading JSON from '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/task.json'
> 2019-10-12 10:16:58,022 - root - DEBUG - {'bash_template_fn': 'template.sh',
>  'inputs': {'falcon_asm_done': '../../../2-asm-falcon/falcon_asm_done',
>             'rawread_db': '../../../0-rawreads/build/raw_reads.db'},
>  'outputs': {'rawread_id_file': 'rawread_ids'},
>  'parameters': {'pypeflow_mb': 4000, 'pypeflow_nproc': 1, 'topdir': '../../..'}}
> 2019-10-12 10:16:58,023 - root - INFO - CD: '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids' <- '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids'
> 2019-10-12 10:16:58,023 - root - DEBUG - Checking existence of '../../../2-asm-falcon/falcon_asm_done' with timeout=30
> 2019-10-12 10:16:58,023 - root - DEBUG - Checking existence of '../../../0-rawreads/build/raw_reads.db' with timeout=30
> 2019-10-12 10:17:28,058 - root - ERROR - Was waiting for '../../../0-rawreads/build/raw_reads.db'
```
```py
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 69, in wait_for
>     _wait_for(fn, timeout)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 85, in _wait_for
>     raise Exception('Timed out waiting for {!r}'.format(fn))
> Exception: Timed out waiting for '../../../0-rawreads/build/raw_reads.db'
> 2019-10-12 10:17:28,059 - root - INFO - CD: '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids' -> '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids'
> 2019-10-12 10:17:28,059 - root - CRITICAL - Error in /root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
> Traceback (most recent call last):
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/root/miniconda3/envs/dna/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
>     main()
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
>     run(**vars(parsed_args))
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
>     run_cfg_in_tmpdir(cfg, tmpdir, '.')
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 219, in run_cfg_in_tmpdir
>     wait_for(fn)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 69, in wait_for
>     _wait_for(fn, timeout)
>   File "/root/miniconda3/envs/dna/lib/python3.7/site-packages/pypeflow/do_task.py", line 85, in _wait_for
>     raise Exception('Timed out waiting for {!r}'.format(fn))
> Exception: Timed out waiting for '../../../0-rawreads/build/raw_reads.db'
```
```sh
> +++ pwd
> ++ echo 'FAILURE. Running top in /public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
> ++ rm -f top.txt
> ++ which python
> ++ which top
> ++ env -u LD_LIBRARY_PATH top -b -n 1
> ++ env -u LD_LIBRARY_PATH top -b -n 1
> ++ pstree -apl
> 
> real	0m30.740s
> user	0m0.320s
> sys	0m0.275s
> + finish
> + echo 'finish code: 1'
```

**Comment by pb-cdunn** [comment]
```
Exception: Timed out waiting for '../../../0-rawreads/build/raw_reads.db'
```
You are missing that file (w.r.t. `/public/home/FALCON/DBM/3-unzip/reads/dump_rawread_ids/`)
