### ISSUE TITLE
Error when running FALCON_unzip (in 3-unzip/1-hasm)

### ISSUE THREAD

**Issue by daisyko** [PacificBiosciences/FALCON_unzip#155]
I ran FALCON_unzip with default parameters from github and my cfg file is as follow:

```ini
[General]
pwatcher_type = blocking
#job_type = PBS
job_type = local
#job_queue = high.q

[Unzip]
input_fofn= fa.fofn
input_bam_fofn= subreads.bam.fofn
#polish_include_zmw_all_subreads = true

smrt_bin=/lustre/apps/opt/smrtlink/7.0.1/smrtcmds/bin/

[job.defaults]
njobs = 40
pwatcher_type = blocking
use_tmpdir = TRUE
job_queue = high.q
sge_phasing= -pe smp 12
sge_quiver= -pe smp 24
sge_track_reads= -pe smp 12
sge_blasr_aln=  -pe smp 24
sge_hasm=  -pe smp 40
unzip_blasr_concurrent_jobs = 40
unzip_phasing_concurrent_jobs = 40
quiver_concurrent_jobs = 40


submit = /bin/bash -c "${JOB_SCRIPT}" > "${JOB_STDOUT}" 2> "${JOB_STDERR}"

```

However, I got an error of "IndexError: list index out of range" in one step during 1-hasm. The full error message is shown in below:
```py
> Traceback (most recent call last):
>   File "/my/path/to/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/my/path/toanaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/my/path/toanaconda3/lib/python3.7/site-packages/falcon_unzip/mains/ovlp_filter_with_phase_strict.py", line 408, in <module>
>     main()
>   File "/my/path/toanaconda3/lib/python3.7/site-packages/falcon_unzip/mains/ovlp_filter_with_phase_strict.py", line 404, in main
>     run(args)
>   File "/my/path/toanaconda3/lib/python3.7/site-packages/falcon_unzip/mains/ovlp_filter_with_phase_strict.py", line 333, in run
>     arid2phase[row[0]] = (row[1], row[2], row[3])  # ctg_id, phase_blk_id, phase_id
> IndexError: list index out of range
> 2019-12-02 23:28:52,278 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
> 2019-12-02 23:28:52,278 - root - INFO - CD: '/tmp/1154482.1.high.q/uid/pypetmp//my/path/to/falcon_falconunzip/3-unzip/1-hasm' -> '/my/path/to/falcon_falconunzip/3-unzip/1-hasm'
> 2019-12-02 23:28:52,279 - root - INFO - CD: '/my/path/to/falcon_falconunzip/3-unzip/1-hasm' -> '/my/path/to/falcon_falconunzip/3-unzip/1-hasm'
> 2019-12-02 23:28:52,279 - root - CRITICAL - Error in /my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py with args="{'json_fn': '/my/path/to/falcon_falconunzip/3-unzip/1-hasm/task.json',\n 'timeout': 30,\n 'tmpdir': '/tmp/1154482.1.high.q'}"
> Traceback (most recent call last):
>   File "/my/path/to/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/my/path/to/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 280, in <module>
>     main()
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 272, in main
>     run(**vars(parsed_args))
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 266, in run
>     run_cfg_in_tmpdir(cfg, tmpdir, '.')
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
>     run_bash(bash_template, myinputs, myoutputs, parameters)
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/do_task.py", line 200, in run_bash
>     util.system(cmd)
>   File "/my/path/to/anaconda3/lib/python3.7/site-packages/pypeflow/io.py", line 27, in syscall
>     raise Exception(msg)
> Exception: Call '/bin/bash user_script.sh' returned 256.
```

**Comment by pb-cdunn** [comment]
Your code might be out of date from Bioconda. But I'd suggest trying to debug this locally. You can `cd` into the directory of that task and look at `user_script.sh` to see how `ovlp_filter_with_phase_strict.py` was run. You should be able to look at the rid-to-phase file to see why it's parsed wrong.

**Comment by daisyko** [comment]
Hi,
Thank you for your reply. I checked my `ovlp_filter_with_phase_strict.py` and found that it was empty. Is there any suggestion for editing the file? Should I add something in it? Thanks.

**Comment by te-tuyama** [comment]
Hi,

same error here. Any idea how to fix that?

Thanks,

**Comment by chichizhao** [comment]
hello，have you guys solve this problem? I meet the same problem here , I have check the file, rid_to_phase.all which is empty. I decided to not use this program for  following steps unzip polish and phase. if you guys solve this problem, please let me konw, i really appreciate about that
