### ISSUE TITLE
falcon-unzip failed at 3-unzip/reads/get_read_ctg_map

### ISSUE THREAD

**Issue by Jinxian52099** [PacificBiosciences/FALCON_unzip#165]
Hello,

I ran falcon successfully, but falcon-unzip failed at 3-unzip/reads/get_read_ctg_map. Following is the stderr file in 3-unzip/reads/get_read_ctg_map directory. How can I solve this problem? Thank you very much!

> Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/falcon_kit/mains/generate_read_to_ctg_map.py", line 97, in <module>
    main()
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/falcon_kit/mains/generate_read_to_ctg_map.py", line 93, in main
    run(**vars(args))
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/falcon_kit/mains/generate_read_to_ctg_map.py", line 33, in run
    oid = rid_to_oid[rid]
IndexError: list index out of range
2020-09-23 22:30:25,358 - root - WARNING - Call '/bin/bash user_script.sh' returned 256.
2020-09-23 22:30:25,358 - root - INFO - CD: '/home/Falcon_assembly//3-unzip/reads/get_read_ctg_map' -> '/home/Falcon_assembly//3-unzip/reads/get_read_ctg_map'
2020-09-23 22:30:25,358 - root - INFO - CD: '/home/Falcon_assembly//3-unzip/reads/get_read_ctg_map' -> '/home/Falcon_assembly//3-unzip/reads/get_read_ctg_map'
2020-09-23 22:30:25,359 - root - CRITICAL - Error in /home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py with args="{'json_fn': '/home/Falcon_assembly//3-unzip/reads/get_read_ctg_map/task.json',\n 'timeout': 30,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py", line 280, in <module>
    main()
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py", line 272, in main
    run(**vars(parsed_args))
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py", line 266, in run
    run_cfg_in_tmpdir(cfg, tmpdir, '.')
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py", line 241, in run_cfg_in_tmpdir
    run_bash(bash_template, myinputs, myoutputs, parameters)
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/do_task.py", line 200, in run_bash
    util.system(cmd)
  File "/home/xxx/miniconda3/envs/falcon/lib/python3.8/site-packages/pypeflow/io.py", line 27, in syscall
    raise Exception(msg)
Exception: Call '/bin/bash user_script.sh' returned 256.
pwd
+++ pwd
++ echo 'FAILURE. Running top in /home/Falcon_assembly//3-unzip/reads/get_read_ctg_map (If you see -terminal database is inaccessible- you are using the python bin-wrapper, so you will not get diagnostic info. No big deal. This process is crashing anyway.)'
++ rm -f top.txt
++ which python
++ which top
++ env -u LD_LIBRARY_PATH top -b -n 1
++ env -u LD_LIBRARY_PATH top -b -n 1
++ pstree -apl

real    0m47.326s
user    0m43.308s
sys     0m8.652s
+ finish
+ echo 'finish code: 1'

**Comment by pb-cdunn** [comment]
Look for stderr in the task-directory, `3-unzip/reads/get_read_ctg_map/*`
