### ISSUE TITLE
fail to open a sam file

### ISSUE THREAD

**Issue by IEkAdN** [PacificBiosciences/FALCON_unzip#65]
Hello.

FALCON_unzip fails with the error below(`4-quiver/track_reads_h/pwatcher.dir/stderr`). I think it failed to create a sam file for some reason.
How can I avoid this problem ?

.
.
.
samfile_fn:'/scratch/hoge/FU_1701151949/4-quiver/reads/000613F_002.sam'
samfile_fn:'/scratch/hoge/FU_1701151949/4-quiver/reads/000053F_008.sam'
samfile_fn:'/scratch/hoge/FU_1701151949/4-quiver/reads/000083F_022.sam'
[E::hts_open_format] fail to open file '/scratch/hoge/FU_1701151949/4-quiver/reads/000083F_022.sam'
/scratch/hoge/FU_1701151949/4-quiver/track_reads_h/track_reads_h.sh: line 9:  7124 segmentation fault               fc_select_reads_from_bam.py --basedir ../.. /scratch/hoge/FU_1701151949/input_bam.fofn
touch /scratch/hoge/FU_1701151949/4-quiver/track_reads_h/track_reads_h_done.exit
+ touch /scratch/hoge/FU_1701151949/4-quiver/track_reads_h/track_reads_h_done.exit
2017-01-19 05:14:24,967 - root - DEBUG - CD: '/scratch/hoge/FU_1701151949/4-quiver/track_reads_h' -> '/scratch/hoge/FU_1701151949/4-quiver/track_reads_h'
2017-01-19 05:14:24,967 - root - DEBUG - CD: '/scratch/hoge/FU_1701151949/4-quiver/track_reads_h' -> '/scratch/hoge/FU_1701151949/4-quiver/track_reads_h'
2017-01-19 05:14:24,968 - root - CRITICAL - Error in /data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/scratch/hoge/FU_1701151949/4-quiver/track_reads_h/task.json',\n 'timeout': 60,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/data/hoge/tools/Python-2.7.9_build/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/data/hoge/tools/Python-2.7.9_build/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/data/hoge/tools/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 35584 <- '/bin/bash -vex /scratch/hoge/FU_1701151949/4-quiver/track_reads_h/track_reads_h.sh'

real  234m16.529s
user  931m6.059s
sys 37m34.987s
 returned: 256

**Comment by pb-jchin** [comment]
You samtools or pysam installation may not be able to handle the files.

**Comment by IEkAdN** [comment]
Thank you for your quick reply.
I added `${FALCON_unzip_38de578_install_dir}/lib/python2.7/site-packages` to the top of PYTHONPATH,
and assigned `${smrtlink_3.1.1_install_dir}/smrtcmds/bin` to `smrt_bin` in `fc_unzip.cfg`.
Doesn't it mean that I ran FALCON_unzip with the expected version of samtools and pysam ?

**Comment by IEkAdN** [comment]
In the directory `${FALCON_unzip_38de578_install_dir}/lib/python2.7/site-packages`,
there is a directory `pysam-0.9.1.4-py2.7-linux-x86_64.egg/`,
so I thought pysam was automatically installed when I installed FALCON_unzip.
Is it right ?
