### ISSUE TITLE
FALCON_unzip successful with Ecoli sample, but failed with my own data

### ISSUE THREAD

**Issue by wsuplantpathology** [PacificBiosciences/FALCON_unzip#73]
Hi @pb-jchin @pb-cdunn ,

Please help me with this issue, I was running falcon_unzip 0.4.0, and was successful using Ecoli example data after falcon running. However, it was failed when I ran my own data, even though I was using exactly the same environment, the same dependencies, and the same falcon-kit. Here is what I got in 3-unzip/reads/pwatcher.dir/stderr :

`[40293]finished track_reads
python -m falcon_kit.mains.pr_ctg_track
+ python -m falcon_kit.mains.pr_ctg_track
/usr/bin/python: No module named ext_falcon
touch /data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/track_reads_done.exit
+ touch /data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/track_reads_done.exit
2017-03-15 22:25:07,803 - root - DEBUG - CD: '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads' -> '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads'
2017-03-15 22:25:07,803 - root - DEBUG - CD: '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads' -> '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads'
2017-03-15 22:25:07,804 - root - CRITICAL - Error in /home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/task.json',\n 'timeout': 600000000000000,\n 'tmpdir': None}"
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 190, in <module>
    main()
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 182, in main
    run(**vars(parsed_args))
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 136, in run
    run_cfg_in_tmpdir(cfg, tmpdir)
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 160, in run_cfg_in_tmpdir
    run_python_func(func, myinputs, myoutputs, parameters)
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py", line 125, in run_python_func
    do_support.run_bash(script_fn)
  File "/home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_support.py", line 51, in run_bash
    raise Exception('{} <- {!r}'.format(rc, cmd))
Exception: 256 <- '/bin/bash -vex /data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/track_reads.sh'

real	109m20.759s
user	411m47.694s
sys	12m34.778s
 returned: 256
`

For comparison, here is what I got from successful ecoli example, from 3-unzip/reads/pwatcher.dir/stderr:

`[40185]finished track_reads
#mkdir -p 3-unzip/reads/
python -m falcon_kit.mains.fetch_reads
+ python -m falcon_kit.mains.fetch_reads
cd /data/chen/software/FALCON-integrate/test/3-unzip/reads
+ cd /data/chen/software/FALCON-integrate/test/3-unzip/reads
date
+ date
touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/track_reads_done
+ touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/track_reads_done
touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/track_reads_done.exit
+ touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/track_reads_done.exit
2017-03-15 20:32:53,799 - root - DEBUG - CD: '/data/chen/software/FALCON-integrate/test/3-unzip/reads' -> '/data/chen/software/FALCON-integrate/test/3-unzip/reads'
2017-03-15 20:32:53,799 - root - DEBUG - Checking existence of u'ctg_list' with timeout=600000000000000
2017-03-15 20:32:53,802 - root - DEBUG - Checking existence of u'track_reads_done' with timeout=600000000000000
2017-03-15 20:32:53,804 - root - DEBUG - CD: '/data/chen/software/FALCON-integrate/test/3-unzip/reads' -> '/data/chen/software/FALCON-integrate/test/3-unzip/reads'

real	6m19.866s
user	4m55.217s
sys	0m28.049s
touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/run.sh.done
+ touch /data/chen/software/FALCON-integrate/test/3-unzip/reads/run.sh.done
 returned: 0`

The only difference between these two runnings was that there were three jobs failed in 0-rawreads step due to LAcheck issue in Falcon, and I manually ran that three jobs and successful (see my comments in falcon issue #124). For Ecoli example, I ran Falcon successfully directly, without any manual steps. 

Please let me know if you need more information. Thanks very much in advance.
chongjing

**Comment by gconcepcion** [comment]
Hi @wsuplantpathology 

Can you post the contents of: 
/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/task.json

It looks like the task finished successfully.

Does 3-unzip/reads/track_reads_done exist,  and is 3-unzip/reads/ctg_list non-empty?

If so, you may be able to proceed by touching the sentinel and re-invoking the pipeline:
touch /data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/track_reads_done.exit

**Comment by wsuplantpathology** [comment]
Thanks @gconcepcion 

1) Here is the contents of `/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/task.json`
```
{
    "inputs": {
        "falcon_asm_done": "/data/chen/PacBio/PST/assembly/falcon/raw_all/2-asm-falcon/falcon_asm_done"
    },
    "outputs": {
        "ctg_list_file": "ctg_list",
        "job_done": "track_reads_done"
    },
    "parameters": {
        "config": {
            "job_queue": "default",
            "job_type": "local",
            "pwatcher_type": "fs_based",
            "sge_blasr_aln": "-pe smp 24 -q your_sge_queue",
            "sge_hasm": "-pe smp 48 -q your_sge_queue",
            "sge_phasing": "-pe smp 12 -q your_sge_queue",
            "sge_track_reads": "-pe smp 12 -q your_sge_queue",
            "smrt_bin": "/data/chen/software/GenomicConsensus-smrtanalysis-3.0.2/bin",
            "unzip_blasr_concurrent_jobs": 8,
            "unzip_phasing_concurrent_jobs": 8
        },
        "sge_option": "-pe smp 12 -q your_sge_queue",
        "wd": "/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads"
    },
    "python_function": "falcon_unzip.unzip.task_track_reads"
}
```
2) I do have non-empty  `3-unzip/reads/ctg_list`, but `3-unzip/reads/track_reads_done` does not exist. However, I have `3-unzip/reads/track_reads_done.exit` and this file is empty.

3) I ran your last two commands, nothing happens but two empty files generated, `run.sh.done` and `track_reads_done.exit`

Besides, in the 3-unzip/reads/ directory there are many `*F_reads.fa` and `*F_ref.fa` files, and they are non-empty. The name of `*F` are all listed in `ctg_list`. My new questions are, 
1) how do you know the task looks like finished successfully? 
2) what is that critical error in `CRITICAL - Error in /home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/task.json',\n 'timeout': 600000000000000,\n 'tmpdir': None}"`

Thanks very much for your time and efforts, I appreciate.

**Comment by gconcepcion** [comment]
1. Is your SGE queue really called "your_sge_queue", or did you change it just to paste it here? I would say look into this as the obvious culprit. The job is able to track the reads as that's all done on the node from which falcon was executed, but then failed as soon as it tried to set up the rest of the unzip job because the queue setting is wrong? Not sure if this is the case - just a suggestion to investigate.

2. So the run.sh script exited due to an import failure prior to touching the `track_reads_done` file. That's interesting because `python -m falcon_kit.mains.rr_ctg_track` seems to have completely successfully, but then the script chokes on: `python -m falcon_kit.mains.pr_ctg_track` with an ImportError. But both of those scripts import the same python modules so i'm not sure what's happening.

> Besides, in the 3-unzip/reads/ directory there are many *F_reads.fa and *F_ref.fa files, and they are non-empty. however, I notice the first file 000000F_reads.fa is 42Mb, then size of following *F_reads.fa is decreasing, with last one 000544F._reads.fa has only 354kb. Is this normal? The name of *F are all listed in ctg_list. My new questions are,

Yes, this is normal. In general the lowest number contig `000000F` is the longest and thus it has the most reads mapping to it. The number of reads mapping to a particular contig should decrease as the contig number increases. Unless of course the contig is a highly repetitive section of DNA

>how do you know the task looks like finished successfully?

Sorry, I was mistaken - I missed the env error `/usr/bin/python: No module named ext_falcon` 
I'll need to take a look and see if I can figure out what's going on here.

> what is that critical error in CRITICAL - Error in /home/chongjing.xia/FALCON-integrate/pypeFLOW/pypeflow/do_task.py with args="{'json_fn': '/data/chen/PacBio/PST/assembly/falcon/raw_all/3-unzip/reads/task.json',\n 'timeout': 600000000000000,\n 'tmpdir': None}"

That's just saying that the read tracking task exited without completing successfully, due to the issues mentioned above.

**Comment by wsuplantpathology** [comment]
Thanks @gconcepcion for your explanations, very helpful.

> Is your SGE queue really called "your_sge_queue", or did you change it just to paste it here? I would say look into this as the obvious culprit. Not sure if this is the case - just a suggestion to investigate.

No, I just leave these setting as default. I set `job_type = local`. So I didn't change SGE settings in the example .cfg. Actually, we are using SLURM, our partition is called "kamiak". Do you think I should set `job_queue = kamiak`, even though I have `job_type = local`. 

Some update information:
Since you mentioned the track reads step looks successful, so I proceeded the following steps. And it turns out, everything looks good: I got phasing step done, and even quiver consensus. Basically, I have `all_p_ctg.fa` (85Mb, which is a little bit smaller than previously estimated 100Mb), `all_h_ctg.fa` (54Mb, I think this size is good since my fungus has high heterozygosity). But these are my first impression, I'll look into the details of the running process. Any comments are welcome on these results, since I am not so confident on how to interpret these data. 

Thanks very much.
