### ISSUE TITLE
 I start from corrected reads, but unzip doesn't work

### ISSUE THREAD

**Issue by chaijinchao** [PacificBiosciences/FALCON_unzip#82]
hi,
      i run the falcon from corrected reads(input types is preads), and it works very well. But when i run the falcon_unzip(the input fofn is corrected reads), it doesn't work(Checking existence of /0-rawreads/raw_reads.db), and the 0-rawreads is empty, i want to know how can i run the falcon_unzip from corrected read?

**Comment by pb-jchin** [comment]
The phasing part of FALCON-Unzip uses the raw sequences that have the proper het-SNP information.  It can't do phasing with the error correct reads.   You will have to start with the raw sequences so the code can track the raw read through the pipeline.

**Comment by chaijinchao** [comment]
thank you for your answers, and the FALCON and  FALCON-Unzip all must start with the raw sequences?

**Comment by rob123king** [comment]
I linked the rawreads folder from the run that created the preads. This progressed it although have an error, it seemed to work and if the preads were generated from that parent folder then should be fine?
error now
`[ERROR]Task Node(3-unzip/reads) failed with exit-code=32512
[INFO]recently_satisfied: set([])
[INFO]Num satisfied in this iteration: 0
[INFO]Num still unsatisfied: 1
[ERROR]Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
[ERROR]ready: set([])
        submitted: set([])
Traceback (most recent call last):
  File "/home/data/bioinf_resources/programming_tools/falcontest/bin/fc_unzip.py", line 11, in <module>
    load_entry_point('falcon-unzip==0.4.0', 'console_scripts', 'fc_unzip.py')()
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/mains/start_unzip.py", line 25, in main
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 319, in run
  File "/scratch/cdunn/fork/.git/LOCAL4/lib/python2.7/site-packages/falcon_unzip/unzip.py", line 195, in unzip_all
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 273, in refreshTargets
    self._refreshTargets(updateFreq, exitOnFailure)
  File "/home/data/bioinf_resources/programming_tools/falcontest/lib/python2.7/site-packages/pypeflow-1.0.0-py2.7.egg/pypeflow/simple_pwatcher_bridge.py", line 339, in _refreshTargets
    raise Exception(msg)
Exception: Some tasks are recently_done but not satisfied: set([Node(3-unzip/reads)])
`

**Comment by pb-cdunn** [comment]
Look for `stderr` somewhere under `3-unzip/reads`. The problem would probably pop out at you, whatever it is.
